### ISSUE TITLE
No PKG for 3.1 release

### ISSUE THREAD

**Issue by hoodslide** [jamf/Notifier#29]
Assets for [3.1 release](https://github.com/jamf/Notifier/releases) only include source code, no PKG file

**Comment by macmule** [comment]
[Notifier-3.1.pkg.zip](https://github.com/user-attachments/files/17436911/Notifier-3.1.pkg.zip)

@hoodslide attached!

I will add to the release, when I can.. currently I don't have the rights.

**Comment by macmule** [comment]
Added to release now.. looks like I had tried.. but it timed out:

<img width="607" alt="Screenshot 2024-10-21 at 15 20 40" src="https://github.com/user-attachments/assets/9d07fcc4-9dce-4691-b484-5b1fcdb74eda">

But, thanks for the heads up :)
